import path from 'path';
import createError  from 'http-errors';
import express from 'express';
const { createServerIocContainer } = require('ui-platform-core/dist/lib/ui-application/server.ioc-container');
import { uiRouterFactory } from './router/ui-router.factory';



/**
 * Initialize web app based on Express server
 *
 * @param {String} rootPath - root directory of target app
 * @param {String} [configPath] - relative path to specific app config file (within root dir)
 * @param {Object} [assetsManifestPath] - manifest file generated by Webpack ManifestPlugin
 *
 * @returns {express}
 */
export default function({ rootPath, configPath, assetsManifestPath = {} }) {
  const app  = express();
  const baseConfigPath = path.join(rootPath, 'config', 'base.yaml');

  if (! configPath) {
    configPath = baseConfigPath;
  }


  // initialize root IoC container
  const iocContainer = createServerIocContainer({
    baseConfigPath: baseConfigPath,
    configPath: configPath,
    assetsManifestPath
  });


  app.use(express.json());
  app.use(express.urlencoded({ extended: false }));
  app.use(express.static(path.join(rootPath, 'public')));

  app.use('/', uiRouterFactory({
    rootDir: rootPath,
    iocContainer,
  }));

  // catch 404 and forward to error handler
  app.use(function(req, res, next) {
    next(createError(404));
  });

  // error handler
  app.use(function(err, req, res) {
    // set locals, only providing error in development
    res.locals.message = err.message;
    res.locals.error = req.app.get('env') === 'development' ? err : {};

    // render the error page
    res.status(err.status || 500);
    res.json(err);
    console.error(err);
  });

  return app;
}
